// The twin (`permissions.ts`) is generated by `python -m app.auth.permissions --ts` and imported
// by nothing yet — Platform Task 2's `can()`/`guard()` is its first consumer. Until then it is
// still `src/**` and so still under the 100/100/100/100 coverage thresholds (vite.config.ts), and
// an unimported module reports 0 %: this file is what makes `npx vitest run --coverage` pass
// (fix round 1, Critical 1). It is not busywork — the assertions below are the SAME invariants
// `tests/auth/test_permissions.py` pins on the Python side, so a hand-edit of the generated file
// (or a stale regeneration) fails here rather than silently diverging from the server.
import { describe, expect, it } from 'vitest';
import { MATRIX, REAUTH, ROLES } from './permissions';

describe('generated permission twin', () => {
  it('carries the spec §4 rows the server enforces', () => {
    expect(MATRIX['engine.activate']).toEqual(['admin']);
    expect(MATRIX['users.decide']).toEqual(['admin', 'staff']);
    expect(MATRIX['seller.apply']).toEqual(['buyer']);
    expect([...MATRIX['page.gate']].sort()).toEqual([...ROLES].sort());
  });

  it('names only roles that exist, and only permissions that exist', () => {
    const roles = new Set<string>(ROLES);
    const permissions = Object.keys(MATRIX);
    expect(permissions.length).toBeGreaterThan(0);
    for (const [permission, allowed] of Object.entries(MATRIX)) {
      expect(allowed.length, `${permission} grants nobody`).toBeGreaterThan(0);
      for (const role of allowed) expect(roles.has(role), `${permission} names unknown role ${role}`).toBe(true);
    }
    // Every re-auth permission is a real permission: the Python side pins `REAUTH <= set(MATRIX)`
    // (Important 1 — `users.revoke` was in REAUTH and in no matrix row, and the generator hid it).
    for (const permission of REAUTH) expect(permissions, `REAUTH names unknown permission ${permission}`).toContain(permission);
  });

  it('keeps every row sorted and every permission unique, as the generator emits them', () => {
    for (const [permission, allowed] of Object.entries(MATRIX)) {
      expect([...allowed], `${permission} is not sorted`).toEqual([...allowed].sort());
      expect(new Set(allowed).size, `${permission} repeats a role`).toBe(allowed.length);
    }
    expect([...REAUTH]).toEqual([...REAUTH].sort());
  });
});
