// GENERATED by `python -m app.auth.permissions --ts` — do not edit.
export const ROLES = ["anonymous", "applicant", "buyer", "seller", "staff", "admin"] as const;
export type Role = (typeof ROLES)[number];
export type Permission =
  "abuse.investigate" |
  "account.self" |
  "audit.read" |
  "data_sources.read" |
  "engine.activate" |
  "layer.google_live" |
  "layer.satellite" |
  "licence.decide" |
  "listing.manage_own" |
  "listing.publish" |
  "listing.read" |
  "listing.review" |
  "market.read" |
  "page.admin" |
  "page.browse" |
  "page.gate" |
  "page.seller" |
  "permissions.read" |
  "request.answer_own" |
  "request.create" |
  "request.oversee" |
  "request.read_own" |
  "roles.grant" |
  "seller.apply" |
  "tokens.manage" |
  "users.decide" |
  "users.review";
export const MATRIX: Record<Permission, readonly Role[]> = {
  "abuse.investigate": ["admin"],
  "account.self": ["admin", "applicant", "buyer", "seller", "staff"],
  "audit.read": ["admin", "staff"],
  "data_sources.read": ["admin", "staff"],
  "engine.activate": ["admin"],
  "layer.google_live": ["admin", "buyer", "seller", "staff"],
  "layer.satellite": ["admin", "buyer", "seller", "staff"],
  "licence.decide": ["admin"],
  "listing.manage_own": ["seller"],
  "listing.publish": ["admin", "staff"],
  "listing.read": ["admin", "buyer", "seller", "staff"],
  "listing.review": ["admin", "staff"],
  "market.read": ["admin", "buyer", "seller", "staff"],
  "page.admin": ["admin", "staff"],
  "page.browse": ["admin", "buyer", "seller", "staff"],
  "page.gate": ["admin", "anonymous", "applicant", "buyer", "seller", "staff"],
  "page.seller": ["seller"],
  "permissions.read": ["admin", "staff"],
  "request.answer_own": ["seller"],
  "request.create": ["buyer", "seller"],
  "request.oversee": ["admin", "staff"],
  "request.read_own": ["buyer", "seller"],
  "roles.grant": ["admin"],
  "seller.apply": ["buyer"],
  "tokens.manage": ["admin"],
  "users.decide": ["admin", "staff"],
  "users.review": ["admin", "staff"],
};
export const REAUTH: readonly Permission[] = ["engine.activate", "licence.decide", "roles.grant", "tokens.manage"];
