"""The permission matrix — the only place roles meet capabilities (spec §4). `python -m app.auth.permissions --ts` prints the TypeScript twin."""
from __future__ import annotations

import json
import sys

from app.auth.sessions import Principal
from app.config import settings

ROLES = ("anonymous", "applicant", "buyer", "seller", "staff", "admin")
_ALL = frozenset(ROLES)
_MEMBERS = frozenset({"buyer", "seller", "staff", "admin"})
_STAFF = frozenset({"staff", "admin"})
_ADMIN = frozenset({"admin"})

MATRIX: dict[str, frozenset[str]] = {
    "page.gate": _ALL,
    "account.self": _ALL - {"anonymous"},
    "page.browse": _MEMBERS, "listing.read": _MEMBERS,
    "market.read": _MEMBERS,                     # + anonymous while MARKET_DATA_PUBLIC (effective_roles)
    "layer.google_live": _MEMBERS, "layer.satellite": _MEMBERS,
    "request.create": frozenset({"buyer", "seller"}), "request.read_own": frozenset({"buyer", "seller"}),
    "seller.apply": frozenset({"buyer"}),
    "page.seller": frozenset({"seller"}), "listing.manage_own": frozenset({"seller"}), "request.answer_own": frozenset({"seller"}),
    "page.admin": _STAFF, "users.review": _STAFF, "users.decide": _STAFF,
    # Revoke is one branch of the admin Users screen's decide action, split out as its own
    # permission because it — and only it — is in REAUTH (spec §4: "Approve · Decline · Request
    # info · Suspend · Revoke (re-auth for Revoke)"). Fix round 1, Important 1: it was in REAUTH
    # and in no MATRIX row, so `require("users.revoke")` would have raised KeyError at wiring time
    # and the twin's REAUTH list silently omitted it.
    "users.revoke": _STAFF,
    "listing.review": _STAFF, "listing.publish": _STAFF, "request.oversee": _STAFF,
    "abuse.investigate": _ADMIN,
    "data_sources.read": _STAFF,
    "licence.decide": _ADMIN, "engine.activate": _ADMIN, "roles.grant": _ADMIN, "tokens.manage": _ADMIN,
    "audit.read": _STAFF, "permissions.read": _STAFF,
}
REAUTH = frozenset({"licence.decide", "engine.activate", "roles.grant", "tokens.manage", "users.revoke"})
# "users.revoke" joins the list in I3 fix round 1's follow-up (John, 2026-09-06): it is a staff
# decision exactly like "users.decide", which is audited, and I5's decide endpoint writes the audit
# row for its revoke branch. `tests/auth/test_permissions.py` pins both that membership and
# `AUDITED <= set(MATRIX)`, so a name here can no longer drift away from a real permission.
AUDITED = frozenset({"users.review", "users.decide", "users.revoke", "roles.grant", "tokens.manage", "licence.decide", "engine.activate", "abuse.investigate"})
# (method, path template) for every route that is deliberately reachable without a permission.
# `tests/auth/test_permissions.py::test_every_route_is_guarded_or_public` walks `create_app()` and
# fails on anything here that is neither guarded by `require(...)` nor listed below (spec §4
# Enforcement) — fix round 1, Important 8, which is also why the routes that already shipped are
# spelled out rather than waved through by the test.
PUBLIC_ROUTES: frozenset[tuple[str, str]] = frozenset({
    ("GET", "/api/healthz"), ("GET", "/api/healthz/deep"), ("GET", "/robots.txt"), ("GET", "/"), ("GET", "/{path:path}"),
    ("POST", "/api/auth/signup"), ("POST", "/api/auth/verify"), ("POST", "/api/auth/signin"),
    ("POST", "/api/auth/password/forgot"), ("POST", "/api/auth/password/reset"), ("POST", "/api/webhooks/resend"),
    # The other half of `scripts/bootstrap_admin.py` (Task I5): the single-use `invite` token IS
    # the credential, so the caller is anonymous by construction — exactly like `password/reset`.
    ("POST", "/api/auth/accept-invite"),
    ("GET", "/_app/{path:path}"),      # the built bundle (StaticFiles), same public surface as "/" and the SPA catch-all
    ("POST", "/api/interest"),         # the Coming Soon launch-notification sign-up: anonymous by design, rate-limited instead
    # `app.api.health.not_found_router`'s catch-all: it exists so an unknown /api/* path answers a
    # JSON 404 instead of falling through to the SPA's index.html. It reads nothing and writes
    # nothing, on any method.
    *((method, "/api/{path:path}") for method in ("DELETE", "GET", "PATCH", "POST", "PUT")),
})


def effective_roles(principal: Principal | None) -> frozenset[str]:
    if principal is None:
        return frozenset({"anonymous"})
    if principal.state != "active":
        return frozenset({"applicant"})
    return frozenset(principal.roles) | {"applicant"} if principal.roles else frozenset({"applicant"})


def allowed(perm: str, principal: Principal | None) -> bool:
    roles = effective_roles(principal)
    if perm == "market.read" and settings.market_data_public and "anonymous" in roles:
        return True
    return bool(roles & MATRIX[perm])


def to_typescript() -> str:
    perms = sorted(MATRIX)
    lines = ["// GENERATED by `python -m app.auth.permissions --ts` — do not edit.",
             f"export const ROLES = {json.dumps(list(ROLES))} as const;",
             "export type Role = (typeof ROLES)[number];",
             "export type Permission =\n  " + " |\n  ".join(json.dumps(p) for p in perms) + ";",
             "export const MATRIX: Record<Permission, readonly Role[]> = {"]
    lines += [f"  {json.dumps(p)}: {json.dumps(sorted(MATRIX[p]))}," for p in perms]
    # `sorted(REAUTH)`, not `sorted(REAUTH & set(MATRIX))`: the intersection quietly dropped a
    # REAUTH entry that named no permission instead of failing (Important 1). The invariant is
    # pinned by tests/auth/test_permissions.py::test_every_reauth_permission_is_a_real_permission.
    lines += ["};", f"export const REAUTH: readonly Permission[] = {json.dumps(sorted(REAUTH))};", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    if "--ts" in sys.argv:
        sys.stdout.write(to_typescript())
