"""The permission matrix — the only place roles meet capabilities (spec §4). `python -m app.auth.permissions --ts` prints the TypeScript twin."""
from __future__ import annotations

import json
import sys

from app.auth.sessions import Principal
from app.config import settings

ROLES = ("anonymous", "applicant", "buyer", "seller", "staff", "admin")
_ALL = frozenset(ROLES)
_MEMBERS = frozenset({"buyer", "seller", "staff", "admin"})
_STAFF = frozenset({"staff", "admin"})
_ADMIN = frozenset({"admin"})

MATRIX: dict[str, frozenset[str]] = {
    "page.gate": _ALL,
    "account.self": _ALL - {"anonymous"},
    "page.browse": _MEMBERS, "listing.read": _MEMBERS,
    "market.read": _MEMBERS,                     # + anonymous while MARKET_DATA_PUBLIC (effective_roles)
    "layer.google_live": _MEMBERS, "layer.satellite": _MEMBERS,
    "request.create": frozenset({"buyer", "seller"}), "request.read_own": frozenset({"buyer", "seller"}),
    "seller.apply": frozenset({"buyer"}),
    "page.seller": frozenset({"seller"}), "listing.manage_own": frozenset({"seller"}), "request.answer_own": frozenset({"seller"}),
    "page.admin": _STAFF, "users.review": _STAFF, "users.decide": _STAFF,
    "listing.review": _STAFF, "listing.publish": _STAFF, "request.oversee": _STAFF,
    "abuse.investigate": _ADMIN,
    "data_sources.read": _STAFF,
    "licence.decide": _ADMIN, "engine.activate": _ADMIN, "roles.grant": _ADMIN, "tokens.manage": _ADMIN,
    "audit.read": _STAFF, "permissions.read": _STAFF,
}
REAUTH = frozenset({"licence.decide", "engine.activate", "roles.grant", "tokens.manage", "users.revoke"})
AUDITED = frozenset({"users.review", "users.decide", "roles.grant", "tokens.manage", "licence.decide", "engine.activate", "abuse.investigate"})
PUBLIC_ROUTES: frozenset[tuple[str, str]] = frozenset({
    ("GET", "/api/healthz"), ("GET", "/api/healthz/deep"), ("GET", "/robots.txt"), ("GET", "/"), ("GET", "/{path:path}"),
    ("POST", "/api/auth/signup"), ("POST", "/api/auth/verify"), ("POST", "/api/auth/signin"),
    ("POST", "/api/auth/password/forgot"), ("POST", "/api/auth/password/reset"), ("POST", "/api/webhooks/resend"),
})


def effective_roles(principal: Principal | None) -> frozenset[str]:
    if principal is None:
        return frozenset({"anonymous"})
    if principal.state != "active":
        return frozenset({"applicant"})
    return frozenset(principal.roles) | {"applicant"} if principal.roles else frozenset({"applicant"})


def allowed(perm: str, principal: Principal | None) -> bool:
    roles = effective_roles(principal)
    if perm == "market.read" and settings.market_data_public and "anonymous" in roles:
        return True
    return bool(roles & MATRIX[perm])


def to_typescript() -> str:
    perms = sorted(MATRIX)
    lines = ["// GENERATED by `python -m app.auth.permissions --ts` — do not edit.",
             f"export const ROLES = {json.dumps(list(ROLES))} as const;",
             "export type Role = (typeof ROLES)[number];",
             "export type Permission =\n  " + " |\n  ".join(json.dumps(p) for p in perms) + ";",
             "export const MATRIX: Record<Permission, readonly Role[]> = {"]
    lines += [f"  {json.dumps(p)}: {json.dumps(sorted(MATRIX[p]))}," for p in perms]
    lines += ["};", f"export const REAUTH: readonly Permission[] = {json.dumps(sorted(REAUTH & set(MATRIX)))};", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    if "--ts" in sys.argv:
        sys.stdout.write(to_typescript())
